version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo "Build started on $(date)"
      - echo "Listing repo root"
      - ls -la
      - echo "Going into aws/ (where pom.xml is)"
      - cd aws
      - ls -la
      - mvn -v

  build:
    commands:
      - mvn clean package -DskipTests
      - echo "Listing target folder"
      - ls -lah target
      - cp target/*.jar ../app.jar
      - cd ..
      - ls -lah

artifacts:
  files:
    - Procfile
    - app.jar
