version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - mvn -v
      - mvn clean package -DskipTests
      - ls -lh target
      - cp target/*.jar app.jar

artifacts:
  files:
    - Procfile
    - app.jar
